# Generated by Django 4.2.3 on 2023-08-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='sgfsgsd', upload_to='gallary'),
            preserve_default=False,
        ),
    ]
